# Form implementation generated from reading ui file 'c:\Users\reece\DungeonWalker\main_window.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dungeonWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        font = QtGui.QFont()
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.dungeonWidget.setFont(font)
        self.dungeonWidget.setObjectName("dungeonWidget")
        self.dungeonWidget.setColumnCount(0)
        self.dungeonWidget.setRowCount(0)
        self.dungeonWidget.horizontalHeader().setVisible(False)
        self.dungeonWidget.horizontalHeader().setHighlightSections(False)
        self.dungeonWidget.verticalHeader().setVisible(False)
        self.dungeonWidget.verticalHeader().setHighlightSections(False)
        self.gridLayout_2.addWidget(self.dungeonWidget, 0, 0, 1, 1)
        self.moveButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.moveButton.setObjectName("moveButton")
        self.gridLayout_2.addWidget(self.moveButton, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "DungeonWalker"))
        self.moveButton.setText(_translate("MainWindow", "MOVE"))
